import { hashPassword } from './auth.js';
import { HttpError, id, validateEmail } from './utils.js';
const HEADER = '<div class="brand"><b>LABDOX</b><span>Ideas. Built.</span></div><div class="rule"></div>';
const FOOTER = '<div class="footer"><span>Labdox Private Limited</span><span>people@labdox.com · www.labdox.com</span></div>';
const CSS = '.subject{font-weight:700;margin:18px 0}.brand{display:flex;justify-content:space-between;align-items:end;color:#102a43}.brand b{font-size:28px;letter-spacing:3px}.brand span{font-size:10px}.rule{height:4px;background:#0f766e;margin-top:10px}';

export async function ensureInitialData(env) {
  const existing = await env.DB.prepare('SELECT id FROM users LIMIT 1').first();
  if (existing) return;
  if (!env.INITIAL_ADMIN_EMAIL || !env.INITIAL_ADMIN_PASSWORD || String(env.INITIAL_ADMIN_PASSWORD).length < 12) throw new HttpError('Administrator setup is required. Contact the application owner.',503);
  const salt=id('salt'), hash=await hashPassword(env.INITIAL_ADMIN_PASSWORD,salt);
  const statements = [
    env.DB.prepare('INSERT OR IGNORE INTO users (id,email,full_name,password_hash,password_salt,role,must_change_password) VALUES (?,?,?,?,?,?,1)').bind('usr_admin',validateEmail(env.INITIAL_ADMIN_EMAIL),'Administrator',hash,salt,'admin'),
    env.DB.prepare('INSERT OR IGNORE INTO signatories (id,name,designation) VALUES (?,?,?)').bind('sig_hr','HR Team','People Operations')
  ];
  const templates = [
    ['tpl_offer','Standard Offer Letter','Offer Letter','OFFER','LABDOX/HR/{{year}}/{{sequence}}','<p>Dear {{recipient_name}},</p><p>We are pleased to offer you the position of <strong>{{designation}}</strong> at Labdox. Your skills, enthusiasm, and potential stood out during our selection process, and we believe you will make a valuable contribution to the team.</p><p>Your role will involve working closely with your assigned team, taking ownership of agreed responsibilities, and following Labdox policies and professional standards. The detailed terms of your engagement, including your joining date, work arrangement, and applicable benefits, will be communicated separately.</p>','<p>Please confirm your acceptance by signing and returning a copy of this letter. We look forward to welcoming you to Labdox and supporting your professional growth.</p><p>Warm regards,</p>','["sig_hr"]'],
    ['tpl_lor','Letter of Recommendation','Letter of Recommendation','LOR','LABDOX/LOR/{{year}}/{{sequence}}','<p>To whom it may concern,</p><p>We are pleased to recommend <strong>{{recipient_name}}</strong>, who worked with Labdox as <strong>{{designation}}</strong>. During this association, they consistently demonstrated professionalism, responsibility, and a willingness to learn.</p><p>They approached assigned work with care, communicated effectively with colleagues, and responded positively to feedback. Their ability to understand requirements and complete responsibilities within expected timelines made them a dependable member of the team.</p>','<p>Based on their performance and conduct, we are confident that {{recipient_name}} will be a valuable addition to future academic or professional opportunities. We recommend them without reservation and wish them continued success.</p><p>Sincerely,</p>','["sig_hr"]'],
    ['tpl_joining','Standard Joining Letter','Joining Letter','JOIN','LABDOX/HR/{{year}}/{{sequence}}','<p>Dear {{recipient_name}},</p><p>Welcome to Labdox. This letter confirms your joining as <strong>{{designation}}</strong> with effect from the date agreed with the HR Team.</p><p>As part of your onboarding, you will receive information about your reporting structure, responsibilities, internal policies, and the resources required for your role. Please complete the requested documentation and induction formalities within the communicated timelines.</p>','<p>We are delighted to have you join us and hope your journey at Labdox will be engaging, productive, and rewarding. Please contact the HR Team if you need any assistance during onboarding.</p><p>Warm regards,</p>','["sig_hr"]'],
    ['tpl_appointment','Standard Appointment Letter','Appointment Letter','APPT','LABDOX/APPT/{{year}}/{{sequence}}','<p>Dear {{recipient_name}},</p><p>We are delighted to confirm your appointment as <strong>{{designation}}</strong> at Labdox. This appointment reflects our confidence in your ability to contribute effectively to the organisation.</p><p>You will perform the responsibilities assigned to your role, maintain professional conduct, protect confidential information, and comply with applicable company policies. Your detailed terms of appointment and any role-specific conditions form part of the accompanying employment documentation.</p>','<p>Please acknowledge your acceptance by signing and returning a copy of this letter. We look forward to a positive and mutually rewarding association.</p><p>Warm regards,</p>','["sig_hr"]'],
    ['tpl_generic','General Business Letter','Generic Letter','GEN','LABDOX/GEN/{{year}}/{{sequence}}','<p>Dear {{recipient_name}},</p><p>We are writing to formally communicate the following information for your reference and necessary action.</p>','<p>Please contact the HR Team if you require any clarification or supporting information. We appreciate your attention to this matter.</p><p>Warm regards,</p>','["sig_hr"]']
  ];
  for (const t of templates) statements.push(env.DB.prepare(`INSERT OR IGNORE INTO templates
    (id,name,document_type,code,number_prefix,header_html,footer_html,continuation_header_html,continuation_footer_html,default_opening_html,default_closing_html,css,signatory_ids_json,created_by)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(t[0],t[1],t[2],t[3],t[4],HEADER,FOOTER,`<div class="mini-brand">LABDOX · ${t[2]}</div>`,FOOTER,t[5],t[6],CSS,t[7],'usr_admin'));
  await env.DB.batch(statements);
}
